### PR TITLE
Fixed header.html for deprecated .RSSLink

### LINKED ISSUE #6: Deprecation of .RSSLink
In Hugo, the use of .RSSLink is depecrated and will be remove in a future release. Currently building a site with this theme raises a warning:

> WARN 2019/05/24 14:55:47 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like:
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.

### PR DESCRIPTION
**Pull request by patrickderitter**
Fixes #6

### CODE REVIEW

**Comment by patrickderitter** [comment]
Seems this project is abandoned. Closing PR and #6

**Comment by heyarviind** [comment]
Sorry, we were working on another project. Please open the pull request again I'll merge it :)

**Comment by patrickderitter** [comment]
Hi @heyarviind, it seemed like there were no more people connected to uicardiodev. I've reopened the PR and #6.

**Comment by heyarviind** [comment]
Merged thank you for your contributions :)

**Pull request merged**
